name: pixel_paper
description: "A professional document scanning and PDF management project."
publish_to: 'none'
version: 0.9.2+3

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  flutter_expandable_fab: ^2.5.2
  image_picker: ^1.2.1
  pro_image_editor: ^12.0.2
  shared_preferences: ^2.5.4
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  pdf: ^3.11.3
  file_picker: ^10.3.10
  syncfusion_flutter_pdf: ^32.2.5
  printing: ^5.14.2
  path: ^1.9.1
  open_filex: ^4.7.0
  lottie: ^3.1.2
  flutter_staggered_animations: ^1.0.0
  reorderable_grid_view: ^2.0.0
  intl: ^0.20.2
  google_mlkit_text_recognition: ^0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang.json